//
/*! @file FlintOrderItem.h */
//  FlintConnect
//
//  Created by PC Nguyen on 7/13/15.
//  Copyright (c) 2015 Flint. All rights reserved.
//

#import "FlintDomainObject.h"

typedef NS_ENUM(NSInteger, FlintOrderItemType) {
  OrderItemTypeCustomAmount,
  OrderItemTypeCatalog,
  OrderItemTypeCustomDiscount,
  OrderItemTypeCoupon,
};


@interface FlintOrderItem : FlintDomainObject

/**
 *  Item type
 */
@property (assign, nonatomic) FlintOrderItemType itemType;

/**
 *  Item Name
 */
@property (copy, nonatomic) NSString *name;

/**
 *  Price per item
 */
@property (copy, nonatomic) NSNumber *price;

/**
 *  Quantity of items
 */
@property (copy, nonatomic) NSNumber *quantity;

/**
 *  Tax to be applied specifically for this item
 */
@property (copy, nonatomic) NSNumber *taxAmount;

/**
 *  The unique identifier for this order item
 *  This is auto generated by Flint
 */
@property (copy, nonatomic) NSString *uid;

/**
 *  The price before tax, calculated by item price * quantity
 *
 *  @return the subtotal for the item
 */
- (NSNumber *)subTotal;

/**
 *  The price after tax, calculated by subTotal + taxAmount
 *
 *  @return the total value
 */
- (NSNumber *)total;

@end
